context: ../../../../fpga/magic/hardpico_test/ctx.pkl
compiler: iverilog
app:
    name: picorv32_axi
    sources:
        - ../../src/picorv32.v
    parameters:
        COMPRESSED_ISA: 1
        ENABLE_MUL: 1
        ENABLE_FAST_MUL: 1
        ENABLE_DIV: 1
        ENABLE_IRQ: 1
        ENABLE_TRACE: 1
constraints:
    io: io.partial
tests:
    picorv32_test_basic:
        sources:
            - ../../src/picorv32_test_basic.v
        run_flags:
            - +firmware=${PRGA_ROOT}/examples/app/picorv32/src/firmware.hex
            - +max_cycle=1000000
